# Generated by Django 4.2.11 on 2024-04-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50, null=True)),
                ('cur_con', models.CharField(max_length=50, null=True)),
                ('temp', models.IntegerField(null=True)),
                ('humidity', models.IntegerField(null=True)),
                ('wind', models.CharField(max_length=50, null=True)),
                ('forecast', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
